### ISSUE TITLE
Model size and pretrained weights?

### ISSUE THREAD

**Issue by forresti** [gpengzhi/Bi-SimCut#1]
Great work!

I have a couple of questions:

1. For `Bi-SimCut` on WMT14, what is the model size?
2. Are trained weights available for any of the machine translation models?

**Comment by gpengzhi** [comment]
Hi Forrest, thanks for your interest in our work!

1. For the WMT14 experiment, we utilize `transformer_vaswani_wmt_en_de_big` in `fairseq`. And you could download the WMT14 dataset from [here](https://github.com/fe1ixxu/BiBERT#wmt14-data-training). For the training configurations, you could take [this](https://github.com/fe1ixxu/BiBERT/blob/master/train-wmt-dual.sh) for reference and replace the values of some hyperparameters by following the instruction in our paper. 

2. I am sorry that I only have the checkpoint file for the IWSLT'14 de -> en benchmark at hand. I could upload it to google drive and update the README of this repo if needed.

**Comment by forresti** [comment]
Thanks!

**Comment by EliasVansteenkiste** [comment]
> Hi Forrest, thanks for your interest in our work!
> 
> 1. For the WMT14 experiment, we utilize `transformer_vaswani_wmt_en_de_big` in `fairseq`. And you could download the WMT14 dataset from [here](https://github.com/fe1ixxu/BiBERT#wmt14-data-training). For the training configurations, you could take [this](https://github.com/fe1ixxu/BiBERT/blob/master/train-wmt-dual.sh) for reference and replace the values of some hyperparameters by following the instruction in our paper.
> 2. I am sorry that I only have the checkpoint file for the IWSLT'14 de -> en benchmark at hand. I could upload it to google drive and update the README of this repo if needed.

Would it be possible to upload the checkpoint file for the IWSLT'14 de -> en benchmark?
Thank you in advance!

**Comment by gpengzhi** [comment]
Hi Elias, thanks for your interest in our work!

Let me check if I still keep those checkpoint files. If not, I could train a new one for you if needed.

**Comment by gpengzhi** [comment]
> > Hi Forrest, thanks for your interest in our work!
> > 
> > 1. For the WMT14 experiment, we utilize `transformer_vaswani_wmt_en_de_big` in `fairseq`. And you could download the WMT14 dataset from [here](https://github.com/fe1ixxu/BiBERT#wmt14-data-training). For the training configurations, you could take [this](https://github.com/fe1ixxu/BiBERT/blob/master/train-wmt-dual.sh) for reference and replace the values of some hyperparameters by following the instruction in our paper.
> > 2. I am sorry that I only have the checkpoint file for the IWSLT'14 de -> en benchmark at hand. I could upload it to google drive and update the README of this repo if needed.
> 
> Would it be possible to upload the checkpoint file for the IWSLT'14 de -> en benchmark? Thank you in advance!

Hi Elias, thanks for your interest in our work!

Let me check if I still keep those checkpoint files. If not, I could train a new one for you if needed.
